### ISSUE TITLE
'Schedule a status change' not working

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#711]
The "schedule a status change" option isn't working. It's located here:

![image](https://user-images.githubusercontent.com/7929556/65788710-aafb1080-e129-11e9-9a3b-a3684d27e907.png)

I tried to schedule a status change from "draft" to "needs review" for a content author, and "draft" to "published" for a site admin / content editor, and neither worked. I could be setting this up wrong, but it doesn't appear to do anything.

**Comment by davidrkupton** [comment]
I believe this was because there was no cron job.  I have created cron jobs for all 3 environments, so this should now work.

**Comment by andrebtlima** [comment]
Resolved so closing.

**Comment by duffy-james** [comment]
After some re-testing, we confirmed this is still an issue. Functionality not working for content editors and admins. Also, it's showing up for content authors and shouldn't be showing up at all for them.

**Comment by davidrkupton** [comment]
- verified there are no permissions for scheduling for anyone except `content editors`.
- I believe that cron is now operating properly on stg and dev (it was not until yesterday) so it is probable that the schedule part of this will now work.

**Comment by reillyzlab** [comment]
Not working for content author and site admin. 

Scheduling UI off as well as functionality not working:

![Screen Shot 2019-11-23 at 6 19 33 PM](https://user-images.githubusercontent.com/20731897/69486846-47861a00-0e1e-11ea-8653-f372963fac20.png)

![Screen Shot 2019-11-23 at 6 19 12 PM](https://user-images.githubusercontent.com/20731897/69486847-4b19a100-0e1e-11ea-8543-31ef5dacc5d0.png)

**Comment by reillyzlab** [comment]
Fixed

**Comment by reillyzlab** [comment]
Scheduler still not working.

Most of the time the scheduler UI is fine, but miscellaneous times it reverts to including a date in 1970 like the above examples. 

Functionality not working. Attempted to schedule to go from draft to published and from published to draft. Neither worked. 
Tried testing with a page that would be scheduled to be published for the first time as well as overriding an already published page.

Specific most recent tests were completed on the following content types: article and post on MacOS firefox

**Comment by andrebtlima** [comment]
Ok this is working but the clock is off. I scheduled an article to change from Draft to Published at 12:20 pm and it was published at 12:30. So maybe the internal clock is 10 mins off?

**Comment by davidrkupton** [comment]
hey @andrebtlima .  Those tasks are automated by cron which is set to run every 15 mins on the stage/dev environments and every 5 mins on production.  So I guess stage runs on 0,15,30,45,mins past the hour and that's why it published at 12:45 not 12:43.   Actually, you were lucky it was that close ... :)
- In summary, on prod it will be at worst 4 minutes later than requested. (e.g. 12:30 will be published 12:30 but 12:31 will be published 12:35)

**Comment by andrebtlima** [comment]
Resolved so closing
