### ISSUE TITLE
"Last updated" date not appearing on content types unless manually added

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#779]
The "last updated" date is pulled from the "page metadata". It should be appearing at the top right hand side of our content types. If you don't add the updated or published date manually, it just appears as a blank space. 

Here's a post:
![image](https://user-images.githubusercontent.com/7929556/67124362-601c6800-f1c0-11e9-8435-29b7b8e0aa5b.png)

On "Article" pages, there's text but no date:
![image](https://user-images.githubusercontent.com/7929556/67124461-8c37e900-f1c0-11e9-9876-d2ae10b92a36.png)

The "updated" and "published" fields in the metadata should automatically update when the moderation state is changed to "published."

**Comment by davidrkupton** [comment]
I believe this is now fixed.  No dates are added until the page is published.
So until the page is published the updated date is not "Not Published Yet".  If the node is published, then this issue can be taken up by #698.

**Comment by duffy-james** [comment]
@davidrkupton just re-tested this and still seeing an issue. Created a public notice and here's what I get:

![image](https://user-images.githubusercontent.com/7929556/68788546-a1facb80-0611-11ea-8b4d-58a04afd9940.png)

Also, the date didn't update when I published the page:

![image](https://user-images.githubusercontent.com/7929556/68789194-010d1000-0613-11ea-8626-ccc2833d093a.png)

**Comment by reillyzlab** [comment]
Still an issue

**Comment by andrebtlima** [comment]
Still seeing an issue:

<img width="1439" alt="Screen Shot 2019-12-10 at 9 15 12 AM" src="https://user-images.githubusercontent.com/57111927/70536924-a1c8ef80-1b2d-11ea-9640-869914080e37.png">

**Comment by andrebtlima** [comment]
Resolved so closing.
